
spring:
  application:
    name: admin-music-api

  graphql:
    graphiql:
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
server:
  port: 8081